export type ProductContent = {
  description: string;
  features: string[];
  whoFor: string[];
  overview: string;
  keyFeatures: string[];
  aiPlatforms: string[];
  recommendedUseCases: string[];
  implementationGuide: string[];
  productivityBenefits: string[];
  fileFormats: string[];
  skillLevel: string;
  deliveryInfo: string;
  supportInfo: string;
};

export const PRODUCT_CONTENT: Record<number, ProductContent> = {
  1: {
    description: "Starter Prompt Set — 25 AI Prompts for Marketers is a one-time digital purchase in our Prompt Systems lineup, delivered by email immediately after checkout. It includes 25 tested prompts covering everyday marketing writing tasks, built as an entry point into structured AI-assisted content production.",
    overview: "The Starter Prompt Set is your on-ramp to systematic, AI-driven marketing. These 25 prompts cover the core tasks that every marketer repeats daily: drafting social posts, summarizing research, generating campaign ideas, and polishing copy. Each prompt is structured to produce repeatable, high-quality outputs rather than hit-or-miss results. Whether you are running solo campaigns or supporting a broader marketing team, this set replaces guesswork with a proven starting framework.",
    features: ["25 ready-to-use prompts for common marketing tasks", "Organized by use case for quick reference", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Compatible with major AI writing tools"],
    whoFor: ["Solo marketers", "New content creators", "Small business owners"],
    keyFeatures: [
      "25 production-ready prompts organized by task type",
      "Structured input/output formatting so results are consistently usable",
      "Lightweight, scannable reference layout for desk-side use",
      "Zero learning curve — prompts work immediately in any major AI platform",
      "Designed for daily, repeatable use rather than one-off experiments",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity", "Copilot", "Any LLM with prompt-compatible input"],
    recommendedUseCases: [
      "Daily social post drafting",
      "Campaign ideation sprints",
      "Email copy and subject-line brainstorming",
      "Content repurposing from long-form to short-form",
      "Team onboarding for new content creators",
    ],
    implementationGuide: [
      "Download the prompt set via the link in your confirmation email.",
      "Open the file in a plain-text editor or PDF viewer.",
      "Copy the prompt closest to your task and paste it into your AI platform of choice.",
      "Fill in the bracketed variables with your specific campaign, audience, or product context.",
      "Iterate on the AI output and refine until it matches your brand standards.",
    ],
    productivityBenefits: [
      "Cuts first-draft time for common marketing tasks from hours to minutes",
      "Eliminates blank-page syndrome on busy days",
      "Standardizes output quality across writers and campaigns",
      "Reduces dependence on last-minute creative energy",
      "Creates a reusable prompt library that grows with your team",
    ],
    fileFormats: ["PDF", "TXT/CSV"],
    skillLevel: "Beginner to Intermediate",
    deliveryInfo: "Digital delivery via email within minutes of purchase. The download link never expires.",
    supportInfo: "Support is available at support@intelligentprocontentautomation.com. We respond within one business day.",
  },
  2: {
    description: "Email Subject Line Prompt Pack (50 Prompts) is a one-time digital purchase in our Prompt Systems lineup, delivered by email immediately after checkout. It includes 50 structured prompts for generating high-performing subject lines across campaign types.",
    overview: "Email subject lines determine whether your message gets opened or ignored. This pack gives you 50 rigorously tested prompts that generate subject lines optimized for open rates, curiosity, urgency, and value. Rather than staring at a blank composer every send, marketers can draw from a curated prompt bank tailored to specific email types — welcome sequences, cart recovery, newsletters, and re-engagement campaigns.",
    features: ["50 subject line prompts across campaign types", "Organized by goal: open rate, urgency, curiosity", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Compatible with major AI writing tools"],
    whoFor: ["Email marketers", "Lifecycle marketing teams", "Newsletter operators"],
    keyFeatures: [
      "50 prompts organized by campaign goal (open rate, urgency, curiosity, value, personalization)",
      "Includes category-specific suggestions for newsletters, promotions, transactional emails, and re-engagement campaigns",
      "Optimized for spam-filter avoidance and inbox placement",
      "Ready-to-use in under 30 seconds per subject line",
      "Compatible with every major AI email assistant",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity", "Any LLM prompt tool"],
    recommendedUseCases: [
      "A/B test subject-line variants in minutes",
      "Newsletter send optimization",
      "Promotional campaign launches",
      "Re-engagement sequence refreshes",
      "Reducing unsubscribe rates",
    ],
    implementationGuide: [
      "Receive the prompt pack via email immediately after purchase.",
      "Save the file to your campaign planning folder.",
      "Open your email platform and your AI assistant side by side.",
      "Select the prompt category matching your campaign goal.",
      "Paste, fill in the context variables, and generate options.",
      "Test the top 2-3 variants in your next send.",
    ],
    productivityBenefits: [
      "Generates more subject-line options per hour than manual brainstorming",
      "Improves open-rate variety across campaigns",
      "Reduces creative block during launches",
      "Speeds up A/B test setup",
      "Data-backed prompt structure improves consistency",
    ],
    fileFormats: ["PDF", "TXT/CSV"],
    skillLevel: "Beginner to Intermediate",
    deliveryInfo: "Instant email delivery with a permanent download link.",
    supportInfo: "Contact support@intelligentprocontentautomation.com for questions or guidance.",
  },
  3: {
    description: "Blog Ideation Framework — 30 Topic Generators is a one-time digital purchase in our Content Frameworks lineup, delivered by email immediately after checkout. It includes 30 structured topic-generation frameworks for building an editorial pipeline that never runs dry.",
    overview: "A blog without an idea pipeline stalls. This framework supplies 30 repeatable topic-generation systems — each one a different angle for extracting high-value content ideas from your audience, competitors, keyword data, and industry trends. Use these generators to populate a 12-week editorial calendar in under an hour and give your writers a structured brief every single time.",
    features: ["30 structured topic-generation frameworks", "Includes a topic-scoring worksheet", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Content Frameworks"],
    whoFor: ["Content marketers", "SEO writers", "Editorial teams"],
    keyFeatures: [
      "30 distinct topic-generation frameworks covering audience, competitor, keyword, and trend angles",
      "Built-in scoring worksheet to prioritize high-impact topics",
      "Formatted as editable templates for direct copy-paste use",
      "Compatible with SEO tools and Google Trends for data-backed ideation",
      "Designed for populating multi-week editorial calendars quickly",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity", "Copilot"],
    recommendedUseCases: [
      "Populating a quarterly editorial calendar",
      "Breaking through writer's block",
      "Generating topic clusters around target keywords",
      "Aligning blog strategy with product launches",
      "Onboarding new blog writers with a proven ideation system",
    ],
    implementationGuide: [
      "Download the file and open the 30 generator templates.",
      "Input your niche, audience profile, and top keywords into the relevant generators.",
      "Run the AI prompts and collect 5-10 ideas per generator.",
      "Score each topic using the included worksheet (audience size, intent, effort).",
      "Rank and schedule the top 8-12 topics into your editorial calendar.",
      "Repeat monthly to keep a rolling backlog of fresh ideas.",
    ],
    productivityBenefits: [
      "Eliminates the monthly 'what should we write about?' meeting",
      "Produces a high-priority topic list in under one hour",
      "Improves content consistency and trend alignment",
      "Reduces writer dependency on spontaneous inspiration",
      "Scales ideation across multiple writers and verticals",
    ],
    fileFormats: ["PDF", "Notion Template", "DOCX", "Google Sheets"],
    skillLevel: "Intermediate",
    deliveryInfo: "Instant digital delivery by email immediately after purchase.",
    supportInfo: "Email support@intelligentprocontentautomation.com for assistance.",
  },
  4: {
    description: "Social Media Content Calendar Framework is a one-time digital purchase in our Content Frameworks lineup, delivered by email immediately after checkout. It includes a full editorial calendar structure plus weekly planning worksheets for organizing social output.",
    overview: "This framework gives you a complete, editable social media content calendar built around proven posting rhythms and content-type rotations. Inside, you will find a master monthly calendar, weekly planning worksheets, content-type grids (educational, promotional, community, and behind-the-scenes), and a caption/hashtag planning sheet for every major platform.",
    features: ["Full editorial calendar framework", "Weekly planning worksheets included", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Content Frameworks"],
    whoFor: ["Social media managers", "Community managers", "Small marketing teams"],
    keyFeatures: [
      "Master monthly social content calendar with content-type rotation",
      "Weekly planning worksheets for efficient batch scheduling",
      "Platform-specific grids (Instagram, LinkedIn, TikTok, X/Twitter, Facebook)",
      "Caption and hashtag planning sheet per platform",
      "Includes a capacity calculator to match output to team bandwidth",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok"],
    recommendedUseCases: [
      "Monthly content planning sessions",
      "Batch-creating a month of posts in a single sitting",
      "Aligning social output with product launches and campaigns",
      "Cross-team coordination between marketing and sales",
      "Onboarding new social media coordinators",
    ],
    implementationGuide: [
      "Download the framework and open the master monthly calendar.",
      "Fill in key dates, launches, and campaign deadlines for the month.",
      "Use the weekly planning worksheet to assign content types to each day.",
      "Run the AI caption prompts per platform to generate post copy.",
      "Review, schedule, and adjust based on real performance data.",
      "Repeat monthly, refining based on engagement metrics.",
    ],
    productivityBenefits: [
      "Reduces weekly planning time from 3-4 hours to under one hour",
      "Improves content-type balance across the month",
      "Eliminates last-minute 'what do we post today?' scrambling",
      "Makes cross-team handoffs seamless",
      "Creates a reusable annual planning template",
    ],
    fileFormats: ["PDF", "Notion Template", "Canva Template", "Google Sheets"],
    skillLevel: "Beginner to Intermediate",
    deliveryInfo: "Delivered instantly by email with a permanent download link.",
    supportInfo: "Reach out at support@intelligentprocontentautomation.com for help.",
  },
  5: {
    description: "Brand Voice Prompt Toolkit (40 Prompts) is a one-time digital purchase in our Prompt Systems lineup, delivered by email immediately after checkout. It includes 40 prompts designed to define, document, and consistently apply a brand's voice across content.",
    overview: "Inconsistent brand voice is one of the top reasons content fails to build trust. This toolkit gives you 40 modular prompts for documenting your brand voice, applying it across content types, reviewing copy for consistency, and training team members to write in the brand's exact tone. The toolkit covers everything from voice definition sessions to ongoing copy audits.",
    features: ["40 prompts for defining and applying brand voice", "Includes a brand voice reference worksheet", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Compatible with major AI writing tools"],
    whoFor: ["Brand and marketing managers", "Agencies managing client voice", "Content teams with multiple writers"],
    keyFeatures: [
      "40 prompts split across voice definition, application, and audit phases",
      "Brand voice reference worksheet for stakeholder alignment",
      "Tone, vocabulary, and audience-adaptation guidance embedded in each prompt",
      "Works with AI writing assistants for real-time voice coaching",
      "Includes a multi-writer consistency scoring system",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity"],
    recommendedUseCases: [
      "Brand voice workshops and documentation",
      "Onboarding new writers to an established brand",
      "Auditing existing content for consistency",
      "Client voice setup for agencies",
      "Adapting tone across different audience segments",
    ],
    implementationGuide: [
      "Start with the voice-definition prompts to build a brand voice brief.",
      "Use the application prompts to generate copy in that voice.",
      "Share the reference worksheet with writers and stakeholders.",
      "Run periodic audits with the evaluation prompts.",
      "Iterate the voice brief quarterly as the brand evolves.",
    ],
    productivityBenefits: [
      "Reduces revision cycles caused by tone inconsistencies",
      "Accelerates new writer ramp-up",
      "Strengthens audience trust through consistent messaging",
      "Simplifies client voice maintenance for agencies",
      "Provides a measurable voice-quality framework",
    ],
    fileFormats: ["PDF", "DOCX", "Notion Template", "Google Docs"],
    skillLevel: "Intermediate to Advanced",
    deliveryInfo: "Instant email delivery with non-expiring download link.",
    supportInfo: "Email support@intelligentprocontentautomation.com for questions.",
  },
  6: {
    description: "SEO Content Brief Framework — Complete System is a one-time digital purchase in our Content Frameworks lineup, delivered by email immediately after checkout. It includes a full content brief structure plus keyword and search-intent worksheets for writers and editors.",
    overview: "This complete system standardizes how your team plans, writes, and optimizes SEO content. It includes a master content brief template, keyword research worksheets, search-intent mapping guides, and an editorial QA checklist — everything needed to transform a keyword target into a ranking, high-quality piece.",
    features: ["Complete SEO content brief structure", "Keyword and search-intent worksheets included", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Content Frameworks"],
    whoFor: ["SEO content teams", "In-house editors", "Content agencies"],
    keyFeatures: [
      "Master content brief template covering every required section",
      "Keyword research worksheet for primary, secondary, and LSI variants",
      "Search-intent mapping guide (informational, commercial, transactional)",
      "On-page SEO checklist with title tag, meta, header, and image guidance",
      "Editorial QA rubric for scoring draft quality",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity"],
    recommendedUseCases: [
      "Standardizing SEO content production across a team",
      "Onboarding freelance writers to internal SEO standards",
      "Scaling content output without sacrificing quality",
      "Aligning SEO and editorial strategy",
      "Auditing legacy content for SEO gaps",
    ],
    implementationGuide: [
      "Download the full system and open the master brief template.",
      "Paste your target keyword and run the keyword worksheet.",
      "Map the keyword to search intent and outline the brief.",
      "Assign the brief to a writer and set QA milestones.",
      "Run the editorial QA checklist before publishing.",
      "Track rankings and refine the brief format quarterly.",
    ],
    productivityBenefits: [
      "Reduces brief creation time from hours to minutes",
      "Aligns writers, editors, and SEO strategists to one unified brief",
      "Improves on-page SEO consistency across the content library",
      "Scales production capacity without adding headcount",
      "Builds a search-ranking content pipeline with repeatable quality",
    ],
    fileFormats: ["PDF", "Notion Template", "DOCX", "Google Sheets", "Canva"],
    skillLevel: "Intermediate to Advanced",
    deliveryInfo: "Instantly delivered by email with a permanent download link.",
    supportInfo: "Contact support@intelligentprocontentautomation.com for help.",
  },
  7: {
    description: "Content Repurposing Workflow — 7-Channel System is a one-time digital purchase in our Workflow Tools lineup, delivered by email immediately after checkout. It includes a step-by-step workflow for turning one core piece of content into assets for seven distribution channels.",
    overview: "One pillar article can feed an entire month of social, email, short-form video, and podcast content. This system is a repeatable 7-channel repurposing workflow that maps a single asset to Instagram, LinkedIn, TikTok, X/Twitter, email, YouTube Shorts, and a newsletter feature. Each channel has its own format rules, tone adjustments, and scheduling guidance.",
    features: ["Step-by-step 7-channel repurposing workflow", "Covers turning one asset into multiple formats", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Workflow Tools"],
    whoFor: ["Content production teams", "Solo creators scaling output", "Marketing agencies"],
    keyFeatures: [
      "7-channel mapping matrix from one core asset",
      "Format-specific guidance and tone adjustments per channel",
      "Batch-processing worksheet for efficient multi-channel production",
      "Included content calendar template for scheduling repurposed pieces",
      "Templates for clip scripts, quote graphics, and email snippets",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok"],
    recommendedUseCases: [
      "Maximizing ROI on long-form content investment",
      "Filling a 30-day social calendar from one pillar article",
      "Scaling short-form video from webinars and interviews",
      "Reducing per-asset creation cost across channels",
      "Clients requesting multi-channel content packages",
    ],
    implementationGuide: [
      "Select your core pillar asset (blog, video, webinar, podcast).",
      "Open the 7-channel mapping matrix and identify the output formats.",
      "Use the AI prompt per channel to adapt the core content.",
      "Fill in the batch worksheet to track progress across all assets.",
      "Schedule each format using the included content calendar.",
      "Review performance weekly and refine the repurposing ratio.",
    ],
    productivityBenefits: [
      "Multiplies content output from a single creation session",
      "Reduces content production costs by up to 70%",
      "Improves cross-channel message consistency",
      "Eliminates the need to create separate content calendars per platform",
      "Frees up time for strategic work and creative refinement",
    ],
    fileFormats: ["PDF", "Notion Template", "DOCX", "Google Sheets"],
    skillLevel: "Intermediate",
    deliveryInfo: "Delivered instantly by email after purchase.",
    supportInfo: "Email support@intelligentprocontentautomation.com for any questions.",
  },
  8: {
    description: "Lead Magnet Creation Toolkit is a one-time digital purchase in our Operations Kits lineup, delivered by email immediately after checkout. It includes structured templates and a planning framework for building lead magnets that support list growth.",
    overview: "Lead magnets only work if they deliver real value fast. This toolkit provides a structured planning process and proven templates for designing ebooks, checklists, templates, mini-courses, and assessments that convert visitors into subscribers. Each template is built around a clear problem-to-solution format that positions your brand as the expert.",
    features: ["Structured lead magnet planning templates", "Includes distribution checklist", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Operations Kits"],
    whoFor: ["Demand generation marketers", "Course creators", "Growth-focused small businesses"],
    keyFeatures: [
      "Planning framework for identifying the highest-converting magnet format",
      "Editable templates for ebooks, checklists, assessments, and swipe files",
      "Problem-to-solution structure built into every template",
      "Distribution and promotion checklist for maximizing downloads",
      "Form and landing-page hook templates for conversion",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok"],
    recommendedUseCases: [
      "Launching a new lead generation funnel",
      "Revitalizing an underperforming magnet",
      "Building a content upgrade for blog posts",
      "Creating a tripwire offer for list growth",
      "Designing lead magnets for client campaigns",
    ],
    implementationGuide: [
      "Start with the planning worksheet to define your audience, promise, and format.",
      "Choose the matching template (ebook, checklist, assessment, etc.).",
      "Use AI to draft the magnet content in hours instead of days.",
      "Customize the landing page hook and form fields.",
      "Publish and promote using the distribution checklist.",
      "Track downloads and A/B test headlines and offers.",
    ],
    productivityBenefits: [
      "Cuts lead magnet creation time from weeks to a single session",
      "Improves conversion rates through proven problem-to-solution structure",
      "Scales lead generation without large production teams",
      "Creates a library of reusable magnet templates",
      "Data-backed planning reduces guesswork on format choice",
    ],
    fileFormats: ["PDF", "DOCX", "Canva", "Google Docs", "Notion Template"],
    skillLevel: "Beginner to Intermediate",
    deliveryInfo: "Instant email delivery with a permanent download link.",
    supportInfo: "Support available at support@intelligentprocontentautomation.com.",
  },
  9: {
    description: "Weekly Content Planning System is a one-time digital purchase in our Workflow Tools lineup, delivered by email immediately after checkout. It includes a repeatable weekly planning structure that keeps content production on schedule.",
    overview: "This system replaces chaotic weekly planning meetings with a structured, repeatable workflow. It guides your team from backlog review through task assignment, draft scheduling, and review milestones — all in a single, fillable weekly planning document. Batch-scheduling and capacity planning are built in, so output always matches the team's actual bandwidth.",
    features: ["Repeatable weekly planning structure", "Includes a production checklist", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Workflow Tools"],
    whoFor: ["Content managers", "Marketing teams of any size", "Independent content creators"],
    keyFeatures: [
      "Weekly planning worksheet with backlog, assignment, and milestone sections",
      "Built-in capacity calculator to match output to team bandwidth",
      "Content-type rotation guidance for variety and freshness",
      "Progress tracker for draft, review, and publish milestones",
      "Batch-scheduling recommendations for social and email",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini"],
    recommendedUseCases: [
      "Weekly content team standups and planning sessions",
      "Solo creator weekly content batching",
      "Aligning content production with campaign deadlines",
      "Tracking writer progress across a content team",
      "Forecasting monthly output from weekly capacity",
    ],
    implementationGuide: [
      "Download the weekly planning worksheet and open it at the start of each week.",
      "Review the content backlog and flag priority items for the week.",
      "Use the capacity calculator to assign tasks that fit team bandwidth.",
      "Set draft deadlines and review milestones on the tracker.",
      "Run a quick Friday check-in to measure completion and shift blocked items.",
      "Repeat weekly, refining the system based on team velocity data.",
    ],
    productivityBenefits: [
      "Reduces weekly planning overhead from hours to 15 minutes",
      "Improves on-time publish rates by 30%+",
      "Eliminates forgotten content from the backlog",
      "Makes team capacity visible and actionable",
      "Creates a predictable content production cadence month over month",
    ],
    fileFormats: ["PDF", "Google Sheets", "Notion Template", "Excel"],
    skillLevel: "Beginner",
    deliveryInfo: "Instantly delivered to your email after purchase.",
    supportInfo: "Email support@intelligentprocontentautomation.com for any questions.",
  },
  10: {
    description: "Sales Page Copy Framework — Full Structure is a one-time digital purchase in our Content Frameworks lineup, delivered by email immediately after checkout. It includes a complete section-by-section structure for writing sales pages that guide a reader from headline to close.",
    overview: "High-converting sales pages follow a proven psychological structure — not random copy. This framework walks you through every section of a sales page: hero headline, pain-point framing, value proposition, social proof, objection handling, offer stacking, urgency triggers, and close. Each section comes with formulas, word-count guidance, and proven examples.",
    features: ["Complete section-by-section sales page structure", "Includes headline and objection-handling prompts", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Content Frameworks"],
    whoFor: ["Copywriters", "Product marketers", "Founders writing their own pages"],
    keyFeatures: [
      "Full sales page section map: headline, intro, pain, solution, proof, offer, close",
      "Headline formulas and A/B prompt variants for the hero section",
      "Objection-handling and FAQ frameworks embedded in the structure",
      "Social proof placement guidance and formatting templates",
      "Offer-stack and urgency framework for maximizing conversions",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity"],
    recommendedUseCases: [
      "Writing a new sales page from a proven structure",
      "Refactoring an underperforming page",
      "Training new copywriters on sales-page anatomy",
      "Creating sales pages for digital product launches",
      "Building a repeatable copy process for agency clients",
    ],
    implementationGuide: [
      "Download the framework and open the section-by-section map.",
      "Fill in your product details, audience profile, and key differentiators.",
      "Work through each section in order, using the AI prompts for draft copy.",
      "Populate social proof and objections from customer research.",
      "A/B test headline and close variants before full launch.",
      "Track conversion rate and refine sections that underperform.",
    ],
    productivityBenefits: [
      "Reduces sales page drafting time from days to hours",
      "Improves page conversion rates through proven structure",
      "Eliminates the 'where do I start' blank-page problem",
      "Builds a repeatable copy process across pages and products",
      "Aligns copy, design, and development teams to one shared structure",
    ],
    fileFormats: ["PDF", "DOCX", "Google Docs", "Notion Template"],
    skillLevel: "Intermediate to Advanced",
    deliveryInfo: "Instantly delivered by email after purchase.",
    supportInfo: "Support at support@intelligentprocontentautomation.com.",
  },
  11: {
    description: "Newsletter Content Engine — 12-Week System is a one-time digital purchase in our Workflow Tools lineup, delivered by email immediately after checkout. It includes a 12-week structured plan for producing a consistent newsletter without starting from a blank page.",
    overview: "Consistency is the currency of newsletter growth — and this system delivers it. A full 12-week editorial plan, topic bank, send-schedule template, and onboarding flow for new subscribers. Each week is pre-mapped with content themes, hook prompts, and a CTA structure so your newsletter writes itself.",
    features: ["12-week structured newsletter plan", "Includes topic bank and send-schedule template", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Workflow Tools"],
    whoFor: ["Newsletter writers", "Community builders", "Content marketers"],
    keyFeatures: [
      "12-week editorially planned content calendar with weekly themes",
      "Topic bank with 60+ evergreen and trending ideas",
      "Send-schedule template for optimizing open and click rates",
      "Subscriber onboarding email sequence template",
      "Hook, body, and CTA structure for every issue",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity"],
    recommendedUseCases: [
      "Launching a new newsletter with a pre-mapped 12-week schedule",
      "Refreshing an existing newsletter with a structured plan",
      "Scaling newsletter frequency without burnout",
      "Building a subscriber onboarding flow",
      "Training new newsletter writers on a proven system",
    ],
    implementationGuide: [
      "Download the 12-week plan and review the weekly themes.",
      "Schedule send dates using the optimal-day guidance in the template.",
      "At the start of each week, pull the topic from the topic bank.",
      "Use the hook/body/CTA structure to draft the issue in under 30 minutes.",
      "Review, test, and send.",
      "Track opens and clicks to refine topic selection over time.",
    ],
    productivityBenefits: [
      "Reduces newsletter drafting time from 2+ hours to under 30 minutes per issue",
      "Improves content consistency across a 12-week publishing schedule",
      "Eliminates last-minute newsletter scrambling",
      "Builds a reusable topic bank that compounds over time",
      "Enhances subscriber retention through systematic value delivery",
    ],
    fileFormats: ["PDF", "Notion Template", "Google Docs", "Google Sheets"],
    skillLevel: "Beginner to Intermediate",
    deliveryInfo: "Instantly delivered by email after purchase.",
    supportInfo: "Email support@intelligentprocontentautomation.com for assistance.",
  },
  12: {
    description: "Agency Content Operations Toolkit is a one-time digital purchase in our Operations Kits lineup, delivered by email immediately after checkout. It includes the frameworks, prompts, and checklists an agency needs to run client content production consistently.",
    overview: "Running content for multiple clients without a system means reinventing the wheel every time a new brief arrives. This toolkit gives agencies a complete operations layer: client onboarding documents, content brief templates, editorial calendars, approval workflows, QA scorecards, and account management checklists. Everything needed to scale client output without quality slipping.",
    features: ["Full agency content operations framework", "Includes client onboarding and QA checklists", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Operations Kits"],
    whoFor: ["Content and marketing agencies", "Fractional content teams", "Multi-client freelance writers"],
    keyFeatures: [
      "Client onboarding and intake template",
      "Content brief and approval workflow templates",
      "Multi-client editorial calendar with capacity management",
      "QA scorecard for consistent quality across writers",
      "Reporting and performance dashboard template",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity"],
    recommendedUseCases: [
      "Standardizing agency client onboarding",
      "Scaling writer output across multiple accounts",
      "Maintaining consistent quality across a growing team",
      "Automating client reporting cycles",
      "Onboarding new account managers to your process",
    ],
    implementationGuide: [
      "Download the full toolkit and customize the client onboarding template for your agency.",
      "Apply the content brief and workflow templates to each new client.",
      "Use the QA scorecard for every draft before client delivery.",
      "Track production metrics using the reporting dashboard template.",
      "Refine the system based on client feedback and delivery speed.",
      "Document changes and train your team on the standardized workflow.",
    ],
    productivityBenefits: [
      "Reduces client onboarding time from days to hours",
      "Maintains consistent quality across multiple writers and accounts",
      "Scales output capacity without linearly scaling headcount",
      "Eliminates missed deadlines through structured milestone tracking",
      "Builds an agency asset that makes your practice more valuable and sellable",
    ],
    fileFormats: ["PDF", "Notion Template", "DOCX", "Google Sheets", "Canva"],
    skillLevel: "Intermediate to Advanced",
    deliveryInfo: "Instantly delivered by email after purchase.",
    supportInfo: "Please contact support@intelligentprocontentautomation.com for help.",
  },
  13: {
    description: "Full Funnel Copy Framework — Top to Bottom is a one-time digital purchase in our Content Frameworks lineup, delivered by email immediately after checkout. It includes structured copy frameworks for every funnel stage, from top-of-funnel awareness content to bottom-of-funnel conversion copy.",
    overview: "Different funnel stages require completely different copy psychology. This framework maps proven copy structures to each stage: awareness, interest, consideration, intent, evaluation, and purchase. Every stage gets its own headline formula, body structure, CTA framework, and psychological trigger guidance.",
    features: ["Copy frameworks for every funnel stage", "Includes messaging map worksheet", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Content Frameworks"],
    whoFor: ["Growth marketers", "Copywriters", "Founders building a full funnel"],
    keyFeatures: [
      "Six-stage funnel copy map (awareness through purchase)",
      "Headline and CTA formulas tailored to each stage",
      "Messaging map worksheet to align value props across the funnel",
      "Objection-handling frameworks for the consideration and evaluation stages",
      "CTA hierarchy and urgency guidance for conversion optimization",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity"],
    recommendedUseCases: [
      "Writing a complete funnel from scratch",
      "Auditing funnel copy for stage-appropriate messaging",
      "Training new copywriters on funnel copy psychology",
      "Aligning marketing and sales messaging across a funnel",
      "Refactoring an underperforming funnel with better copy structure",
    ],
    implementationGuide: [
      "Download the framework and open the funnel-stage mapping guide.",
      "Map your existing content or planned assets to each funnel stage.",
      "Use the messaging map worksheet to align value props and pain points.",
      "Draft copy stage by stage using the AI prompts and formulas.",
      "Implement and A/B test the awareness and conversion stages first.",
      "Review performance data and refine copy every 30 days.",
    ],
    productivityBenefits: [
      "Reduces funnel copy writing time by half or more",
      "Improves conversion alignment between stages",
      "Eliminates stage-mismatch errors (e.g., hard-selling cold traffic)",
      "Speeds up funnel iteration through a structured revision process",
      "Builds a reusable funnel copy library for future campaigns",
    ],
    fileFormats: ["PDF", "DOCX", "Google Docs", "Notion Template"],
    skillLevel: "Intermediate to Advanced",
    deliveryInfo: "Instantly delivered by email after purchase.",
    supportInfo: "Email support@intelligentprocontentautomation.com.",
  },
  14: {
    description: "AI Content Strategy Playbook is a one-time digital purchase in our Operations Kits lineup, delivered by email immediately after checkout. It includes a complete strategic framework for planning, prioritizing, and operating an AI-assisted content program.",
    overview: "Most teams treat AI as a novelty rather than a strategic lever. This playbook gives you a complete operating framework for AI content — from governance and use-case selection to process design, team training, and performance measurement. It covers risk management, brand alignment, and ROI tracking so AI adoption is measured and repeatable.",
    features: ["Complete AI content strategy framework", "Includes prioritization and planning worksheets", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Operations Kits"],
    whoFor: ["Heads of content and marketing", "Strategy consultants", "Growing content teams"],
    keyFeatures: [
      "AI use-case prioritization matrix to identify highest-impact applications",
      "Content process redesign framework for AI-augmented workflows",
      "Brand guardrails and governance checklist",
      "Team training and prompt-adoption playbook",
      "Performance measurement and ROI tracking template",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity", "OpenAI API", "Any enterprise AI tool"],
    recommendedUseCases: [
      "Designing an organization-wide AI content strategy",
      "Convincing leadership to approve AI content investment",
      "Training a content team on structured AI adoption",
      "Setting guardrails for AI-generated content quality",
      "Measuring and reporting AI content ROI",
    ],
    implementationGuide: [
      "Download the playbook and complete the current-state audit worksheet.",
      "Identify top 3-5 AI use cases using the prioritization matrix.",
      "Present the strategy and roadmap to leadership for alignment.",
      "Pilot the AI workflow on one low-risk content type for 30 days.",
      "Measure output quality, speed, and cost before scaling.",
      "Roll out to the team with training sessions and a prompt library.",
    ],
    productivityBenefits: [
      "Reduces content production costs by 30-50% on supported tasks",
      "Eliminates AI adoption guesswork through a proven framework",
      "Builds team AI competence faster than ad-hoc experimentation",
      "Improves content output velocity without increasing headcount",
      "Creates a defensible, measurable AI content operating model",
    ],
    fileFormats: ["PDF", "Notion Template", "DOCX", "Google Slides"],
    skillLevel: "Advanced",
    deliveryInfo: "Instant email delivery with a permanent download link.",
    supportInfo: "Email support@intelligentprocontentautomation.com for guidance.",
  },
  15: {
    description: "90-Day Content Launch System is a one-time digital purchase in our Workflow Tools lineup, delivered by email immediately after checkout. It includes a full 90-day structured plan for taking a content initiative from kickoff to a repeatable production cadence.",
    overview: "Most content programs fail because they start without a full 90-day plan. This system walks you through a proven three-phase launch: Foundation (days 1-30), Acceleration (days 31-60), and Scale (days 61-90). Each phase includes weekly milestones, content deliverables, and team handoff points.",
    features: ["Full 90-day structured launch plan", "Includes week-by-week milestone worksheets", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Workflow Tools"],
    whoFor: ["Teams launching a new content initiative", "Marketing leads", "Consultants onboarding new clients"],
    keyFeatures: [
      "90-day phased plan: Foundation, Acceleration, and Scale",
      "Weekly milestone worksheets with deliverables and owners",
      "Content calendar and asset checklist per phase",
      "Team handoff and review schedule",
      "Launch readiness checklist and go-live workflow",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok"],
    recommendedUseCases: [
      "Launching a new brand blog, newsletter, or content channel",
      "Onboarding a new client to a content engagement",
      "Rescuing an underperforming content program",
      "Aligning a team around a shared content launch timeline",
      "Consultants delivering a repeatable content kickoff process",
    ],
    implementationGuide: [
      "Download the 90-day system and review the three-phase structure.",
      "Customize the week-by-week worksheet with your specific launch date.",
      "Assign owners and set internal deadlines using the milestone schedule.",
      "Start with Phase 1: audience research, voice brief, and 90-day content backlog.",
      "Move into Phase 2: publish cadence, distribution setup, and performance tracking.",
      "Lock in Phase 3: scale high-performing formats and automate repeatable tasks.",
    ],
    productivityBenefits: [
      "Reduces launch planning from weeks to hours",
      "Eliminates scope creep and missed milestones",
      "Aligns teams around a shared 90-day timeline",
      "Builds a repeatable content launch process you can reuse",
      "Increases the probability of hitting launch goals by 3x or more",
    ],
    fileFormats: ["PDF", "Notion Template", "Google Sheets", "Trello/Asana Import"],
    skillLevel: "Intermediate",
    deliveryInfo: "Instantly delivered by email after purchase.",
    supportInfo: "Email support@intelligentprocontentautomation.com for questions.",
  },
  16: {
    description: "Complete Intelligent Content Suite — All Systems is a one-time digital purchase in our Operations Kits lineup, delivered by email immediately after checkout. It includes every prompt system, content framework, and workflow tool in the IntelliPro catalog in a single bundle.",
    overview: "This is the definitive IntelliPro bundle — everything in one purchase. You get all 16 systems: prompt sets, content frameworks, workflow tools, and operations kits. It is the fastest path to a fully standardized, AI-powered content operation and the most cost-effective way to equip your entire team.",
    features: ["Includes every current prompt system and framework", "Includes every current workflow tool and operations kit", "Instant digital delivery by email after purchase", "One-time purchase — no recurring charges", "Category: Operations Kits"],
    whoFor: ["Agencies running multiple accounts", "Content leads standardizing a whole team", "Creators who want the entire catalog"],
    keyFeatures: [
      "All 16 IntelliPro systems in one bundle",
      "Full prompt library, content frameworks, workflow tools, and operations kits",
      "Master implementation guide for deploying all systems together",
      "Exclusive bundle pricing vs. individual purchases",
      "Lifetime access with no recurring charges or subscriptions",
    ],
    aiPlatforms: ["ChatGPT", "Claude", "Gemini", "Grok", "Perplexity", "Copilot", "Any major AI writing platform"],
    recommendedUseCases: [
      "Equipping an entire content team with a shared system",
      "Running multiple client accounts from one unified content stack",
      "Standardizing content operations across an organization",
      "Building a freelance content business with repeatable deliverables",
      "Maximum ROI for users who want the full catalog",
    ],
    implementationGuide: [
      "Download the complete bundle via your confirmation email link.",
      "Start with the AI Content Strategy Playbook to plan your rollout.",
      "Deploy prompt systems first for immediate daily use.",
      "Add content frameworks and workflow tools in Phase 2 (weeks 2-4).",
      "Integrate operations kits and QA processes in Phase 3 (weeks 5-8).",
      "Measure and optimize using the playbook's ROI tracking tools.",
    ],
    productivityBenefits: [
      "One purchase unlocks every content system you will ever need",
      "Reduces total catalog cost vs. buying individually",
      "Creates a fully standardized content operation in weeks, not months",
      "Eliminates the need to shop for additional content tools",
      "Builds a permanent, reusable content infrastructure for any scale",
    ],
    fileFormats: ["PDF", "Notion Template", "DOCX", "Google Sheets", "Canva", "Google Docs"],
    skillLevel: "Intermediate to Advanced",
    deliveryInfo: "Instant email delivery with a non-expiring download link.",
    supportInfo: "Dedicated support at support@intelligentprocontentautomation.com.",
  },
};
